# Generated by Django 4.1.2 on 2022-10-11 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='fee',
            new_name='course_fee',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='std_course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Join_date',
            new_name='std_joindate',
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_address', models.CharField(max_length=255)),
                ('st_gender', models.CharField(max_length=255)),
                ('st_phone', models.CharField(max_length=255)),
                ('st_photo', models.ImageField(null=True, upload_to='image/')),
                ('st_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
